#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "RoyMcCrain"
email = "me@rrrr.dev"

[ui]
default-command = "log"
pager = "less -FRX"
diff-editor = ["nvim", "-d", "$left", "$right"]
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[aliases]
diffn = ["diff", "--git", "--config=ui.pager=delta -n"]
diffs = ["diff", "--git", "--config=ui.pager=delta -s"]

[remotes.origin]
auto-track-bookmarks = "glob:*"
